calc_vel:
  ros__parameters:
    i_gain_theta: 0.0
    i_gain_x: 0.0
    i_gain_y: 0.0
    length: 0.400
    max_input: 30.0
    p_gain_theta: 0.0
    p_gain_x: 0.0
    p_gain_y: 0.0
    radius: 0.050
