calc_vel:
  ros__parameters:
    p_gain_x: 0.1
    i_gain_x: 0.01
    p_gain_y: 0.1
    i_gain_y: 0.01
    p_gain_theta: 0.1
    i_gain_theta: 0.01
    max_input: 120
    radius: 0.050
    length: 0.400
